communication/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *

urlpatterns = patterns('ecs.communication.views',
    url(r'^list/$', 'list_threads'),
    url(r'^widget/incoming/$', 'incoming_message_widget'),
    url(r'^widget/outgoing/$', 'outgoing_message_widget'),
    url(r'^widget/overview/(?P<submission_pk>\d+)$', 'communication_overview_widget'),

    url(r'^new/(?:(?P<submission_pk>\d+)/)?$', 'new_thread'),
    url(r'^new/(?P<submission_pk>\d+)/to/(?P<to_user_pk>\d+)/$', 'new_thread'),

    url(r'^(?P<thread_pk>\d+)/read/$', 'read_thread'),
    url(r'^(?P<thread_pk>\d+)/close/$', 'close_thread'),
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin
from django.views.static import serve
from django.views.generic.simple import direct_to_template
from django.core.urlresolvers import reverse
from ecs.utils import forceauth
from ecs.utils.viewutils import render

# stuff that needs called at the beginning, but not in settings.py
admin.autodiscover()

def handler500(request):
    ''' 500 error handler which includes ``request`` in the context '''
    from django.template import Context, loader
    from django.http import HttpResponseServerError

    t = loader.get_template('500.html') # You need to create a 500.html template.
    return HttpResponseServerError(t.render(Context({'request': request,})))

def fake404handler(request):
    ''' 404 error fake handler to be called via /trigger404 ''' 
    return render(request, '404.html', {}) 
    

urlpatterns = patterns('',
    # Default redirect is same as redirect from login if no redirect is set (/dashboard/)
    url(r'^$', 'django.views.generic.simple.redirect_to', {'url': settings.LOGIN_REDIRECT_URL}),

    url(r'^', include('ecs.users.urls')),
    url(r'^audit/', include('ecs.audit.urls')),
    url(r'^core/', include('ecs.core.urls')),
    url(r'^checklist/', include('ecs.checklists.urls')),
    url(r'^vote/', include('ecs.votes.urls')),
    url(r'^dashboard/', include('ecs.dashboard.urls')),
    url(r'^feedback/', include('ecs.feedback.urls')),
    url(r'^userswitcher/', include('ecs.userswitcher.urls')),
    url(r'^pdfviewer/', include('ecs.pdfviewer.urls')),
    url(r'^mediaserver/', include('ecs.mediaserver.urls')),
    url(r'^task/', include('ecs.tasks.urls')),
    url(r'^communication/', include('ecs.communication.urls')),
    url(r'^billing/', include('ecs.billing.urls')),
    url(r'^help/', include('ecs.help.urls')),
    url(r'^boilerplate/', include('ecs.boilerplate.urls')),
    url(r'^scratchpad/', include('ecs.scratchpad.urls')),
    url(r'^document/', include('ecs.documents.urls')),
    url(r'^meeting/', include('ecs.meetings.urls')),
    url(r'^notification/', include('ecs.notifications.urls')),
    url(r'^bugshot/', include('ecs.bugshot.urls')),
    url(r'^signature/', include('ecs.signature.urls')),
    url(r'^pki/', include('ecs.pki.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^static/(?P<path>.*)$', forceauth.exempt(serve), {'document_root': settings.MEDIA_ROOT}),

    url(r'^search/', include('haystack.urls')),
)

#if settings.DEBUG: (TODO: does not work, because if DEBUG=False, no trigger500 page is available)
from django.http import HttpResponse
import logging
logger = logging.getLogger(__name__)
def __trigger_log(request):
    logger.warn('foo')
    return HttpResponse()
urlpatterns += patterns('', 
    url(r'^trigger500/$', lambda request: 1/0), 
    url(r'^trigger-warning-log/$', __trigger_log),
    url(r'^trigger404/$', 'ecs.urls.fake404handler'),
)

if 'sentry' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        # redirect sentry login/logout pages to standard pages because we dont want sentry handle login
        #url(r'^sentry/login$', 'django.views.generic.simple.redirect_to', {'url': reverse("ecs.users.views.login")}),
        #url(r'^sentry/logout$', 'django.views.generic.simple.redirect_to', {'url': reverse("ecs.users.views.logout")}),
        url(r'^sentry/', include('sentry.web.urls')),
    )
    
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

if 'debug_toolbar' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^%s(.*)$' % "__debug__/m/", 'debug_toolbar.views.debug_media'),
    )

communication/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.conf import settings
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import force_unicode
from django.core.urlresolvers import reverse

from ecs.communication.models import Message, Thread
from ecs.utils.formutils import require_fields
from ecs.users.utils import get_ec_user
from ecs.users.utils import sudo
from ecs.core.forms.fields import SingleselectWidget


class BaseMessageForm(forms.ModelForm):
    receiver_involved = forms.ModelChoiceField(queryset=User.objects.all(), required=False)
    receiver_person = forms.ModelChoiceField(queryset=User.objects.all(), required=False)
    receiver_type = forms.ChoiceField(choices=(('ek', _('Ethics Commission')),), widget=forms.RadioSelect(), initial='ek')
    receiver = forms.ModelChoiceField(queryset=User.objects.all(), widget=forms.HiddenInput(), required=False)
    
    class Meta:
        model = Message
        fields = ('text',)

    def __init__(self, submission, user, *args, **kwargs):
        self.to_user = kwargs.pop('to', None)
        super(BaseMessageForm, self).__init__(*args, **kwargs)

        self.submission = submission
        self.user = user

        receiver_type_choices = [
            ('ec', '{0} ({1})'.format(force_unicode(_('Ethics Commission')), get_ec_user(submission=self.submission))),
        ]
        receiver_type_initial = 'ec'

        if submission is not None:
            receiver_type_choices += [
                ('involved', _('Involved Party')),
            ]
            receiver_type_initial = 'involved'
            involved_parties = list(submission.current_submission_form.get_involved_parties())
            involved_parties = User.objects.filter(pk__in=[p.user.pk for p in involved_parties if p.user])
            self.fields['receiver_involved'].queryset = involved_parties.exclude(pk=user.pk)

        if user.get_profile().is_internal:
            receiver_type_choices += [
                ('person', _('Person'))
            ]
            self.fields['receiver_person'].queryset = User.objects.exclude(pk=user.pk)
            if getattr(settings, 'USE_TEXTBOXLIST', False):
                self.fields['receiver_person'].widget = SingleselectWidget(url=lambda: reverse('ecs.core.views.internal_autocomplete', kwargs={'queryset_name': 'users'}))

        self.fields['receiver'].queryset = User.objects.exclude(pk=user.pk)

        self.fields['receiver_type'].choices = receiver_type_choices
        self.fields['receiver_type'].initial = receiver_type_initial
        
        if self.to_user:
            self.fields['receiver_type'].required = False

    def clean_receiver(self):
        cd = self.cleaned_data
        
        if self.to_user:
            cd['receiver'] = self.to_user
            return self.to_user
        
        receiver = None
        receiver_type = cd.get('receiver_type', None)

        if receiver_type == 'ec':
            receiver = get_ec_user(submission=self.submission)
        elif receiver_type == 'involved':
            require_fields(self, ['receiver_involved',])
            receiver = cd['receiver_involved']
        elif receiver_type == 'person':
            require_fields(self, ['receiver_person',])
            receiver = cd['receiver_person']

        return receiver

class SendMessageForm(BaseMessageForm):
    subject = Thread._meta.get_field('subject').formfield()

class ReplyDelegateForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea(), label=_('Answer'))

    def __init__(self, user, *args, **kwargs):
        super(ReplyDelegateForm, self).__init__(*args, **kwargs)
        if user.get_profile().is_internal:
            self.fields['to'] = forms.ModelChoiceField(User.objects.all(), required=False, label=_('Delegate to'))
            self.fields.keyOrder = ['to', 'text']
            if getattr(settings, 'USE_TEXTBOXLIST', False):
                self.fields['to'].widget = SingleselectWidget(url=lambda: reverse('ecs.core.views.internal_autocomplete', kwargs={'queryset_name': 'users'}))


class ThreadListFilterForm(forms.Form):
    incoming = forms.BooleanField(required=False)
    outgoing = forms.BooleanField(required=False)
    closed = forms.BooleanField(required=False)
    pending = forms.BooleanField(required=False)

communication/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _

from ecs.utils.viewutils import render, redirect_to_next_url
from ecs.core.models import Submission
from ecs.tasks.models import Task
from ecs.communication.models import Thread
from ecs.communication.forms import SendMessageForm, ReplyDelegateForm
from ecs.tracking.decorators import tracking_hint
from ecs.communication.forms import ThreadListFilterForm
from ecs.communication.utils import send_message
from ecs.utils.security import readonly
from ecs.users.utils import user_flag_required


@readonly(methods=['GET'])
def new_thread(request, submission_pk=None, to_user_pk=None):
    submission, task, reply_to, to_user = None, None, None, None

    if submission_pk is not None:
        submission = get_object_or_404(Submission, pk=submission_pk)
    
    if to_user_pk is not None:
        to_user = get_object_or_404(User, pk=to_user_pk)
    
    task_pk = request.GET.get('task')
    if task_pk is not None:
        task = get_object_or_404(Task, pk=task_pk)
        submission = task.data.get_submission() or submission

    form = SendMessageForm(submission, request.user, request.POST or None, to=to_user)
    thread = None

    if request.method == 'POST' and form.is_valid():
        thread = send_message(request.user, form.cleaned_data['receiver'], form.cleaned_data['subject'], form.cleaned_data['text'], submission=submission, task=task)
        return redirect_to_next_url(request, reverse('ecs.communication.views.read_thread', kwargs={'thread_pk': thread.pk}))

    return render(request, 'communication/send.html', {
        'submission': submission,
        'to_user': to_user,
        'task': task,
        'form': form,
        'thread': thread,
    })


@readonly(methods=['GET'])
def read_thread(request, thread_pk=None):
    thread = get_object_or_404(Thread.objects.by_user(request.user), pk=thread_pk)
    msg = thread.last_message 
    if msg.unread and msg.receiver == request.user:
        msg.unread = False
        msg.save()

    form = ReplyDelegateForm(request.user, request.POST or None)

    if request.method == 'POST' and form.is_valid():
        delegate_to = form.cleaned_data.get('to')
        # delegation is optional; if there is no delegation target, we just
        # append the message to the present thread, else we delegate the
        # present thread and create a new one with the message inside
        if delegate_to:
            thread.delegate(request.user, delegate_to)
            thread = Thread.objects.create(
                subject=_(u'Bzgl.: {0}').format(thread.subject),
                sender=request.user,
                receiver=delegate_to,
                task=thread.task,
                submission=thread.submission,
                related_thread=thread,
            )
        msg = thread.add_message(request.user, text=form.cleaned_data['text'])
        form = ReplyDelegateForm(request.user, None)

    return render(request, 'communication/thread.html', {
        'thread': thread,
        'form': form,
    })


def close_thread(request, thread_pk=None):
    thread = get_object_or_404(Thread.objects.by_user(request.user), pk=thread_pk)
    thread.mark_closed_for_user(request.user)
    return redirect_to_next_url(request, reverse('ecs.communication.views.outgoing_message_widget'))


@readonly()
@tracking_hint(exclude=True)
def incoming_message_widget(request):
    qs = Thread.objects.incoming(request.user).open(request.user)
    submission_pk = request.GET.get('submission', None)
    submission = None
    if submission_pk:
        submission = get_object_or_404(Submission, pk=submission_pk)
        qs = qs.filter(submission=submission)
    return message_widget(request, 
        queryset=qs,
        template='communication/widgets/incoming_messages.inc',
        user_sort='last_message__sender__username',
        session_prefix='dashboard:incoming_messages',
        page_size=4,
        submission=submission,
        extra_context={
            'incoming': True,
            'widget': True,
        }
    )


@readonly()
@tracking_hint(exclude=True)
def outgoing_message_widget(request):
    qs = Thread.objects.outgoing(request.user).open(request.user)
    submission_pk = request.GET.get('submission', None)
    submission = None
    if submission_pk:
        submission = get_object_or_404(Submission, pk=submission_pk)
        qs = qs.filter(submission=submission)
    return message_widget(request, 
        queryset=qs,
        template='communication/widgets/outgoing_messages.inc',
        user_sort='last_message__receiver__username',
        session_prefix='dashboard:outgoing_messages',
        page_size=4,
        submission=submission,
        extra_context={
            'incoming': False,
            'widget': True,
        }
    )


@readonly()
@tracking_hint(exclude=True)
@user_flag_required('is_internal')
def communication_overview_widget(request, submission_pk=None):
    return render(request, 'communication/widgets/overview.inc', {
        'threads': Thread.objects.filter(submission__pk=submission_pk).order_by('-last_message__timestamp'),
    })


@readonly()
def message_widget(request, queryset=None, template='communication/widgets/messages.inc', user_sort=None, session_prefix='messages', extra_context=None, page_size=4, submission=None):
    sort_session_key = '%s:sort' % session_prefix
    raw_sort = request.GET.get('sort', request.session.get(sort_session_key, '-last_message__timestamp'))
    
    sort_options = ('last_message__timestamp', 'user', 'submission')
    sort = raw_sort
    if sort:
        field = sort if sort[0] != '-' else sort[1:]
        if field not in sort_options:
            sort = None
        elif field == 'user':
            sort = sort.replace('user', user_sort) if user_sort else None
    if sort:
        queryset = queryset.order_by(sort)
    request.session[sort_session_key] = sort

    page_session_key = 'dashboard:%s:page' % session_prefix
    try:
        page_num = int(request.GET.get('p', request.session.get(page_session_key, 1)))
    except ValueError:
        page_num = 1

    queryset = queryset.select_related('last_message', 'last_message__sender', 'last_message__receiver',
        'last_message__sender__ecs_profile', 'last_message__receiver__ecs_profile', 'submission')
    paginator = Paginator(queryset, page_size)
    try:
        page = paginator.page(page_num)
    except EmptyPage:
        page_num = paginator.num_pages
        page = paginator.page(page_num)
    request.session[page_session_key] = page_num

    context = {
        'page': page,
        'sort': raw_sort,
        'submission': submission,
    }
    if extra_context:
        context.update(extra_context)
    return render(request, template, context)


@readonly()
def list_threads(request):
    usersettings = request.user.ecs_settings

    filter_defaults = {}
    for key in ('incoming', 'outgoing', 'closed', 'pending'):
        filter_defaults[key] = 'on'

    filterdict = request.POST or usersettings.communication_filter or filter_defaults
    filterform = ThreadListFilterForm(filterdict)
    filterform.is_valid() # force clean

    usersettings.communication_filter = filterform.cleaned_data
    usersettings.save()

    queryset_stage1 = Thread.objects.none()
    if filterform.cleaned_data['incoming']:
        queryset_stage1 |= Thread.objects.incoming(request.user)
    if filterform.cleaned_data['outgoing']:
        queryset_stage1 |= Thread.objects.outgoing(request.user)

    queryset_stage2 = queryset_stage1.none()
    if filterform.cleaned_data['closed'] and filterform.cleaned_data['pending']:
        queryset_stage2 = queryset_stage1
    elif filterform.cleaned_data['closed']:
        queryset_stage2 |= queryset_stage1.filter(Q(closed_by_receiver=True, receiver=request.user) | Q(closed_by_sender=True, sender=request.user))
    elif filterform.cleaned_data['pending']:
        queryset_stage2 |= queryset_stage1.filter(Q(closed_by_receiver=False, receiver=request.user) | Q(closed_by_sender=False, sender=request.user))

    return message_widget(request, 
        template='communication/threads.html',
        queryset=queryset_stage2,
        session_prefix='messages:unified',
        user_sort='receiver__username',
        page_size=15,
        extra_context={'filterform': filterform},
    )

templates/communication/list.html
{% extends "core.html" %}
{% load i18n core communication %}

{% block menuSelection %}communication{% endblock %}

{% block htmltitle %}{% trans "Communication" %} | {{ block.super }}{% endblock %}
{% block headertitle %}{% trans "Communication" %} ({{ page.paginator.count }}){% endblock %}

{% block content %}
  <table class="messages">
      <tr>
          <th>{% trans "Date" %}</th>
          <th>{% trans "Subject" %}</th>
          <th>{% trans "Read" %}</th>
          <th>{% trans "Task" %}</th>
          {% block extra_message_table_headers %}
              <th>Von</th>
              <th>An</th>
          {% endblock %}
          <th></th>
      </tr>
  {% for thread in page.object_list %}
      <tr>
          <td>{{ thread.last_message.timestamp|date:'d.m.Y, H:i:s' }} Uhr</td>
          <td>
              <a href="{% url ecs.communication.views.read_thread thread_pk=thread.pk %}">
                  {% if thread.submission %}{{ thread.submission|ec_number }} - {% endif %}
                  {{ thread.subject }}
              </a>
          </td>
          <td>{{ thread.last_message.unread|yesno:'Nein,Ja' }}</td>
          <td>{{ thread.task|default:'-' }}</td>
          {% block extra_message_table_cells %}
              <td>{{ thread.last_message.sender }}</td>
              <td>{{ thread.last_message.receiver }}</td>
          {% endblock %}
          <td>
              {% block message_actions %}
                  {% if not thread|closed_by:user %}
                  <a class="open-in-widget icon_accept" href="{% url ecs.communication.views.close_thread thread_pk=thread.pk %}?next={{ request.path|urlencode }}" title="{% trans 'mark as done' %}">done</a>
                  {% endif %}
              {% endblock %}
          </td>
      </tr>
  {% endfor %}
  </table>
  
  <div class="paginator">
      {% if page.has_previous %}
          <a class="open-in-widget first_page" href="{{ request.path }}?p=1">first</a>
          <a class="open-in-widget prev_page" href="{{ request.path }}?p={{ page.previous_page_number }}&amp;sort={{ sort }}">previous</a>
      {% endif %}

      Seite {{ page.number }} von {{ page.paginator.num_pages }}
      
      {% if page.has_next %}
          <a class="open-in-widget next_page" href="{{ request.path }}?p={{ page.next_page_number }}&amp;sort={{ sort }}">next</a>
          <a class="open-in-widget last_page" href="{{ request.path }}?p={{ page.paginator.num_pages }}&amp;sort={{ sort }}">last</a>
      {% endif %}
  </div>
  <div class="hint">{% block hint %}{% endblock %}</div>

{% endblock %}

templates/communication/popup.html
{% extends "shell.html" %}

{% block htmlcss %}
    {{ block.super }}
    <style type="text/css">
        body{
            overflow: auto;
        }
    </style>
{% endblock %}

{% block jsbottom %}
{{ block.super }}
<script type="text/javascript">
    window.addEvent('domready', function(){
        $$('a.api').each(function(link){
            link.addEvent('click', function(){
                var request = new Request({
                    url: link.href,
                    onSuccess: function(){
                        window.close();
                    }
                });
                request.send();
                return false;
            });
        })
    });
</script>
{% endblock %}

templates/communication/send.html
{% extends "core.html" %}
{% load i18n core userutils communication %}

{% block menuSelection %}communication{% endblock %}

{% block headertitle %}
    {% if submission %}
        {{ thread.submission|ec_number }} -
    {% endif %}
    {% trans "New Message" %}
{% endblock %}

{% block content %}
<div class="message_display">
  <a href="{% url ecs.communication.views.list_threads %}" class="button_submit">{% trans "Back to the communication overview" %}</a>
  {% if submission %}
      <a href="{% url view_submission submission_pk=submission.pk %}#communication_tab" class="button_submit">{% trans "Back to the Study" %}</a>
  {% endif %}
  <form action="{{ request.path }}" method="post" class="form message open-in-widget">
          {% if submission %}
              <h4>Studie {{ submission|ec_number }}: {{ submission.project_title_display }}</h4>
          {% endif %}

          {% if task %}
          <p>
              <label>Task</label>
              <span>{{ task }}</span>
          </p>
          {% endif %}

          {% if form.subject %}
          <p>
              <label for="{{ form.subject.auto_id }}">Betreff</label>
              {{ form.subject }}
              {% if form.subject.errors %}
                  <span class="errors">{{ form.subject.errors }}</span>
              {% endif %}
          </p>
          {% endif %}

          {% if form.instance.thread %}
            <p>
            <label for="id_participants">antworten an:</label><br />
            </p>
            {% for user in thread.get_participants %}
              <p>
              <input id="id_{{ user.pk }}" type="checkbox" name="{{ user.pk }}"/>
              {% if user|has_flag:'is_internal' %}
                <label for="id_{{ user.pk }}">{{ user.first_name }} {{ user.last_name }}</label><br />
              {% else %}
                <label for="id_{{ user.pk }}">External: {{ user.first_name }} {{ user.last_name }} ({{ user.email }})</label><br />
              {% endif %}
              </p>
            {% endfor %}
          {% endif %}
          
          {% include 'communication/send_base.inc' %}
      <input type="submit" value="Nachricht abschicken" />
  </form>
  <a href="{% url ecs.communication.views.list_threads %}" class="button_submit">{% trans "Back to the communication overview" %}</a>
  {% if submission %}
      <a href="{% url view_submission submission_pk=submission.pk %}#communication_tab" class="button_submit">{% trans "Back to the Study" %}</a>
  {% endif %}
</div>
{% endblock %}

{% block jsbottom %}
    {{ block.super }}
    <script type="text/javascript">
      window.addEvent('domready', function(){
        var container = $$('.message_display')[0];
        ecs.setupMessagePopup(container);
        ecs.setupAutocomplete();

        var messageToolbarItems = [];

        {% if submission %}
            messageToolbarItems.push(ecs.textarea.toolbarItems.annotations("{% trans 'Insert Annotations' %}", '{% url ecs.pdfviewer.views.copy_annotations %}?submission_form_pk={{ submission.current_submission_form.pk }}'));
        {% endif %}

        {% if user|has_flag:'is_internal' %}
            messageToolbarItems.push(ecs.textarea.toolbarItems.boilerplate("{% trans 'Insert Boilerplate' %}", "{% url ecs.boilerplate.views.select_boilerplate %}"));
        {% endif %}

        var textarea = container.getElement('textarea[name="text"]');
        new ecs.textarea.TextArea(textarea);
        ecs.textarea.installToolbar(textarea, messageToolbarItems);
      });
    </script>
{% endblock %}

templates/communication/threads.html
{% extends "communication/list.html" %}
{% load i18n %}

{% block content %}
<div class="messages_overview">
  <div class="messages_header">
    <form id="thread_list_filter" action="" method="post">
        <div class="thread_list_choose">
            {{ filterform.incoming }} <label for="id_incoming" class="thread_incoming"><span class="icon_in"></span>{% trans "Incoming" %}</label>
            {{ filterform.outgoing }} <label for="id_outgoing" class="thread_outgoing"><span class="icon_out"></span>{% trans "Outgoing" %}</label>
        </div>
        <div class="thread_list_choose">
            {{ filterform.pending }} <label for="id_pending" class="thread_outgoing"><span class="icon_pending"></span>{% trans "Pending" %}</label>
            {{ filterform.closed }} <label for="id_closed" class="thread_outgoing"><span class="icon_done"></span>{% trans "Closed" %}</label>
        </div>
    </form>
    <div class="sort_options">
        {% include 'communication/sort_options.inc' %}
    </div>
</div>
{{ block.super }}
</div>
{% endblock %}

{% block extra_message_table_headers %}
    <th>{% trans "Von/An" %}</th>
{% endblock %}

{% block extra_message_table_cells %}
    {% load userutils %}
    {% if thread.last_message.sender == request.user %}
        <td>{% trans "an" %} {{ thread.last_message.receiver }}</td>
    {% else %}
        <td>{% trans "von" %} {{ thread.last_message.sender }}</td>
    {% endif %}
{% endblock %}

{% block hint %}
    <span class="icon_comment"></span>
    {% blocktrans %}
        To write a message, open the read-only view of a study and change to the communication tab.
        For general Questions write an email to the <a href="http://ethikkommission.meduniwien.ac.at/ethik-kommission/kontakt/">Ethics-Commission</a>.
    {% endblocktrans %}
{% endblock %}

{% block jsbottom %}
    {{ block.super }}
    <script type="text/javascript">
      window.addEvent('domready', function(){
          $$('#thread_list_filter input').each(function(input){
              input.addEvent('change', function(){
                  ecs.stopPageLoad();
                  $('thread_list_filter').submit();
              });
          });
      });
    </script>
{% endblock %}